lib/license_web/router.ex
defmodule LicenseWeb.Router do
  use LicenseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(LicenseWeb.Plugs.SetUser)
    plug(LicenseWeb.Plugs.SessionTimeout, timeout_after_seconds: 3_600)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :un_auth do
    plug :put_layout, false
  end

#  entry point
  scope "/", LicenseWeb do
    pipe_through :browser

    get "/", LoaderController, :index
  end

  scope "/login", LicenseWeb do
    pipe_through [:browser, :un_auth]

    get "/", AuthenticationController, :index
    get "/logout", SessionController, :sign_out

  end

  scope "/dashboard", LicenseWeb do
    pipe_through :browser

    get "/", DashboardController, :index
  end

  scope "/register", LicenseWeb do
    pipe_through [:browser, :un_auth]

    get "/", RegisterController, :index
    get "/choose/method", RegisterController, :phase_2
    get "/choose/method/waste-register", RegisterController, :solid_waste_register
  end

  # Other scopes may use custom stacks.
  # scope "/api", LicenseWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LicenseWeb.Telemetry
    end
  end
end

lib/license_web/controllers/register_controller.ex
defmodule LicenseWeb.RegisterController do
  use LicenseWeb, :controller
  use LicenseWeb, :universal

  def index(conn, _params) do
    conn |> render("index.html")
  end

  def phase_2(conn, params) do
    conn |> render("phase_2.html")
  end

  def solid_waste_register(conn, params) do
    conn |> render("solid_waste_register.html")
  end
end

lib/license_web/views/register_view.ex
defmodule LicenseWeb.RegisterView do
  use LicenseWeb, :view
end

lib/license_web/templates/register/index.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>License</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
	<link href="/css/bootstrap.css" rel="stylesheet" type="text/css">
	<link href="/css/core.css" rel="stylesheet" type="text/css">
	<link href="/css/components.css" rel="stylesheet" type="text/css">
	<link href="/css/colors.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script type="text/javascript" src="/js/plugins/loaders/pace.min.js"></script>
	<script type="text/javascript" src="/js/core/libraries/jquery.min.js"></script>
	<script type="text/javascript" src="/js/core/libraries/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/plugins/loaders/blockui.min.js"></script>
	<!-- /core JS files -->


	<!-- Theme JS files -->
	<script type="text/javascript" src="/js/core/app.js"></script>

	<script type="text/javascript" src="/js/plugins/ui/ripple.min.js"></script>
	<!-- /theme JS files -->

</head>

<body class="navbar-bottom">
	<!-- Page header -->
	<div class="page-header">
		<div class="breadcrumb-line">
			<ul class="breadcrumb">
				<li><a href="<%= Routes.authentication_path(@conn, :index) %>"><i class="icon-home2 position-left"></i> login</a></li>
				<li><a href="wizards_steps.html">Waste License</a></li>
				<li class="active">Register</li>
			</ul>

			<ul class="breadcrumb-elements">
				<li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-gear position-left"></i>
						Settings
						<span class="caret"></span>
					</a>

					<ul class="dropdown-menu dropdown-menu-right">
						<li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
						<li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
						<li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
						<li class="divider"></li>
						<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
					</ul>
				</li>
			</ul>
		</div>

		<div class="page-header-content">
			<div class="page-title">
				<h4><a href="<%= Routes.register_path(@conn, :phase_2) %>"><i class="icon-arrow-left52 position-left"></i> </a> </h4>
			</div>

			<div class="heading-elements">
				<div class="heading-btn-group">

				</div>
			</div>
		</div>
	</div>
	<!-- /page header -->

    <!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

			     <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="thumbnail no-padding">
                           <a href="<%= Routes.register_path(@conn, :phase_2) %>">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">WASTE<small class="display-block">SEO specialist</small></h6>
                                <ul class="icons-list mt-15">
                                   <button type="submit" class="btn bg-blue btn-block">Register here!<i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="/images/waste.jpeg" alt="" style="height: 450px; width: 450px;">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">MILK AND MILK PRODUCT <small class="display-block">SEO specialist</small></h6>
                                <ul class="icons-list mt-15">
                                   <button type="submit" class="btn bg-blue btn-block">Register here! <i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="/images/milk.jpeg" alt="" style="height: 450px; width: 450px;">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">MEAT AND MEAT PRODUCT <small class="display-block">SEO specialist</small></h6>
                                <ul class="icons-list mt-15">
                                    <button type="submit" class="btn bg-blue btn-block">Register here! <i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="/images/meat.jpeg" alt="" style="height: 450px; width: 450px;">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">OTHERS <small class="display-block">SEO specialist</small></h6>
                                <ul class="icons-list mt-15">
                                        <button type="submit" class="btn bg-blue btn-block">Register here! <i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="/images/others.jpeg" alt="" style="height: 450px; width: 450px;">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>

				<!-- /error wrapper -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->


</body>
</html>

lib/license_web/templates/register/phase_2.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>License</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
	<link href="/css/bootstrap.css" rel="stylesheet" type="text/css">
	<link href="/css/core.css" rel="stylesheet" type="text/css">
	<link href="/css/components.css" rel="stylesheet" type="text/css">
	<link href="/css/colors.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script type="text/javascript" src="/js/plugins/loaders/pace.min.js"></script>
	<script type="text/javascript" src="/js/core/libraries/jquery.min.js"></script>
	<script type="text/javascript" src="/js/core/libraries/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/plugins/loaders/blockui.min.js"></script>
	<!-- /core JS files -->


	<!-- Theme JS files -->
	<script type="text/javascript" src="/js/core/app.js"></script>

	<script type="text/javascript" src="/js/plugins/ui/ripple.min.js"></script>
	<!-- /theme JS files -->

</head>

<body class="navbar-bottom">

	<!-- Page header -->
	<div class="page-header">
		<div class="breadcrumb-line">
			<ul class="breadcrumb">
				<li><a href="<%= Routes.authentication_path(@conn, :index) %>"><i class="icon-home2 position-left"></i> login</a></li>
				<li><a href="wizards_steps.html">Waste License</a></li>
				<li class="active">Register</li>
			</ul>

			<ul class="breadcrumb-elements">
				<li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-gear position-left"></i>
						Settings
						<span class="caret"></span>
					</a>

					<ul class="dropdown-menu dropdown-menu-right">
						<li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
						<li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
						<li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
						<li class="divider"></li>
						<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
					</ul>
				</li>
			</ul>
		</div>

		<div class="page-header-content">
			<div class="page-title">
				<h4><a href="<%= Routes.register_path(@conn, :phase_2) %>"><i class="icon-arrow-left52 position-left"></i> </a> </h4>
			</div>

			<div class="heading-elements">
				<div class="heading-btn-group">

				</div>
			</div>
		</div>
	</div>
	<!-- /page header -->

    <!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

                <div class="row">
                    <div class="col-lg-4 col-md-6">
                    <a href="<%= Routes.register_path(@conn, :solid_waste_register)%>">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">SOLID WASTE PROVIDERS LICENSE<small class="display-block">Apply Now</small></h6>
                                <ul class="icons-list mt-15">
                                   <button type="submit" class="btn bg-blue btn-block">APPLY NOW<i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="assets/images/placeholder.jpg" alt="">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </a>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">SELF-SERVICE SOLID WASTE PROVIDERS LICENSE<small class="display-block">Apply Now</small></h6>
                                <ul class="icons-list mt-15">
                                   <button type="submit" class="btn bg-blue btn-block">Apply Now! <i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="assets/images/placeholder.jpg" alt="">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="thumbnail no-padding">
                            <div class="caption text-center">
                                <h6 class="text-semibold no-margin">SMALL SCALE ENTERPRISE/PROPRIETOR LICENSE <small class="display-block">Apply Now</small></h6>
                                <ul class="icons-list mt-15">
                                    <button type="submit" class="btn bg-blue btn-block">Apply Now<i class="icon-arrow-right14 position-right"></i></button>
                                </ul>
                            </div>
                            <div class="thumb">
                                <img src="assets/images/placeholder.jpg" alt="">
                                <div class="caption-overflow">
                                    <span>
                                        <a href="assets/images/placeholder.jpg" class="btn bg-success-400 btn-icon btn-xs" data-popup="lightbox"><i class="icon-plus2"></i></a>
                                        <a href="user_pages_profile.html" class="btn bg-success-400 btn-icon btn-xs"><i class="icon-link"></i></a>
                                    </span>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>

				<!-- /error wrapper -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->


</body>
</html>